services:
  app:
    build:
      context: ./docker/php
    working_dir: /var/www
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
    volumes:
      - ./src:/var/www
    depends_on:
      mysql:
        condition: service_healthy

  web:
    image: nginx:1.25-alpine
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  node:
    image: node:20-alpine
    working_dir: /var/www
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "5173:5173"
    volumes:
      - ./src:/var/www
    entrypoint: ["sh","-lc","tail -f /dev/null"]

  mysql:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: secret
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    ports:
      - "13306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
